# Site settings
title: UN OCHA Style guide
baseurl: /styleguide

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - Gruntfile.js
  - css/*.*
  - '*.scss'
