# Site settings
title: UN OCHA Style guide
baseurl: "/styleguide" # the subpath of your site, e.g. /blog/
rw_theme_url: "https://github.com/reliefweb/site/blob/responsive/site/profiles/reliefweb/themes/kobe/"

# Build settings
markdown: kramdown
